version: '3.8'
services:
  frontend:
    build: .  # Construir desde el Dockerfile local
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=app_db
    depends_on:
      - db

  db:
    image: joaquinsr/php-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3307:3306"
